eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
microservice:
 payment-service:
  endpoints:
   endpoint:
    uri: http://PAYMENT-SERVICE/payment/makePayment
  order-service:
   endpoints:
    endpoint:
     uri: http://ORDER-SERVICE/order/saveOrder   
    
